/**
 * Per-workspace cached recent activity digest.
 *
 * Updated by `recent-digest-cron` every 15 minutes from the latest
 * timeline events. Read by loadPromptContext to fill `{{recentDigest}}`
 * in persona system prompts without paying an embed/recall cost on every
 * companion turn.
 *
 * Single row per workspace; the cron upserts. Trade-off: digest is up
 * to 15 minutes stale, which is fine for "what was the user just up to"
 * persona priming. Anything fresher would require a per-turn recall.
 */
import { sql } from 'drizzle-orm';
import { index, integer, pgTable, primaryKey, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import { workspace } from './workspace';

export const workspaceRecentDigest = pgTable('workspace_recent_digest', {
  workspaceId: uuid('workspace_id')
    .primaryKey()
    .references(() => workspace.id, { onDelete: 'cascade' }),
  digest: text('digest').notNull().default(''),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .default(sql`now()`)
    .$onUpdate(() => new Date()),
});

/**
 * AI-synthesized "week in review" narrative shown on /review.
 *
 * One row per (workspace, windowDays). Generated by the Monday cron and
 * regenerable on demand via server action. `inputsHash` lets us skip
 * regeneration when the underlying stats haven't changed.
 */
export const weeklyReviewNarrative = pgTable(
  'weekly_review_narrative',
  {
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    windowDays: integer('window_days').notNull().default(7),
    narrative: text('narrative').notNull(),
    inputsHash: text('inputs_hash').notNull().default(''),
    modelProvider: text('model_provider'),
    modelId: text('model_id'),
    generatedAt: timestamp('generated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [primaryKey({ columns: [t.workspaceId, t.windowDays] })],
);

/**
 * Per-user saved timeline views — a named bundle of /timeline filter
 * params (kinds, projectId, since, q). The URL stays the live source of
 * truth; saved views are just bookmarks that survive devices.
 */
export const timelineSavedView = pgTable(
  'timeline_saved_view',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    userId: uuid('user_id').notNull(),
    name: text('name').notNull(),
    params: text('params').notNull(), // URL query string, e.g. "kinds=a,b&since=7d"
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [index('timeline_saved_view_ws_user_idx').on(t.workspaceId, t.userId)],
);
